/*
 * generated by Xtext 2.13.0
 */
package ac.soton.xtheory.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TheoryGrammarAccess extends AbstractGrammarElementFinder {
	
	public class TheoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Theory");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTheoryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cParametersAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_2_1_0 = (RuleCall)cParametersAssignment_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cImportKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cImportsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cImportsIDTerminalRuleCall_3_1_0 = (RuleCall)cImportsAssignment_3_1.eContents().get(0);
		private final Assignment cImportsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cImportsIDTerminalRuleCall_3_2_0 = (RuleCall)cImportsAssignment_3_2.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cAlternatives_4.eContents().get(0);
		private final Keyword cTypeKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Assignment cInternalElementsAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cInternalElementsTypeParserRuleCall_4_0_1_0 = (RuleCall)cInternalElementsAssignment_4_0_1.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cAlternatives_4.eContents().get(1);
		private final Keyword cOpKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cInternalElementsAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cInternalElementsOperatorParserRuleCall_4_1_1_0 = (RuleCall)cInternalElementsAssignment_4_1_1.eContents().get(0);
		private final Group cGroup_4_2 = (Group)cAlternatives_4.eContents().get(2);
		private final Keyword cAxmKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cInternalElementsAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final RuleCall cInternalElementsAxiomParserRuleCall_4_2_1_0 = (RuleCall)cInternalElementsAssignment_4_2_1.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cAlternatives_4.eContents().get(3);
		private final Keyword cThmKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cInternalElementsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cInternalElementsTheoremParserRuleCall_4_3_1_0 = (RuleCall)cInternalElementsAssignment_4_3_1.eContents().get(0);
		private final Group cGroup_4_4 = (Group)cAlternatives_4.eContents().get(4);
		private final Keyword cRuleblockKeyword_4_4_0 = (Keyword)cGroup_4_4.eContents().get(0);
		private final Assignment cRuleBlocksAssignment_4_4_1 = (Assignment)cGroup_4_4.eContents().get(1);
		private final RuleCall cRuleBlocksRuleBlockParserRuleCall_4_4_1_0 = (RuleCall)cRuleBlocksAssignment_4_4_1.eContents().get(0);
		private final Keyword cEndKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		////import "platform:/ressource/ac.soton.eventb.emf.core.theoryextension/model/eventbcoretheoryextension.ecore"
		//Theory:
		//	'theory' name=ID ('(' parameters+=Parameter+ ')')? ('import' imports+=ID imports+=ID*)? ('type' internalElements+=Type
		//	| 'op' internalElements+=Operator | 'axm' internalElements+=Axiom | 'thm' internalElements+=Theorem | 'ruleblock'
		//	ruleBlocks+=RuleBlock)*
		//	'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'theory' name=ID ('(' parameters+=Parameter+ ')')? ('import' imports+=ID imports+=ID*)? ('type' internalElements+=Type |
		//'op' internalElements+=Operator | 'axm' internalElements+=Axiom | 'thm' internalElements+=Theorem | 'ruleblock'
		//ruleBlocks+=RuleBlock)* 'end'
		public Group getGroup() { return cGroup; }
		
		//'theory'
		public Keyword getTheoryKeyword_0() { return cTheoryKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//('(' parameters+=Parameter+ ')')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_0() { return cLeftParenthesisKeyword_2_0; }
		
		//parameters+=Parameter+
		public Assignment getParametersAssignment_2_1() { return cParametersAssignment_2_1; }
		
		//Parameter
		public RuleCall getParametersParameterParserRuleCall_2_1_0() { return cParametersParameterParserRuleCall_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_2() { return cRightParenthesisKeyword_2_2; }
		
		//('import' imports+=ID imports+=ID*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'import'
		public Keyword getImportKeyword_3_0() { return cImportKeyword_3_0; }
		
		//imports+=ID
		public Assignment getImportsAssignment_3_1() { return cImportsAssignment_3_1; }
		
		//ID
		public RuleCall getImportsIDTerminalRuleCall_3_1_0() { return cImportsIDTerminalRuleCall_3_1_0; }
		
		//imports+=ID*
		public Assignment getImportsAssignment_3_2() { return cImportsAssignment_3_2; }
		
		//ID
		public RuleCall getImportsIDTerminalRuleCall_3_2_0() { return cImportsIDTerminalRuleCall_3_2_0; }
		
		//('type' internalElements+=Type | 'op' internalElements+=Operator | 'axm' internalElements+=Axiom | 'thm'
		//internalElements+=Theorem | 'ruleblock' ruleBlocks+=RuleBlock)*
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//'type' internalElements+=Type
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//'type'
		public Keyword getTypeKeyword_4_0_0() { return cTypeKeyword_4_0_0; }
		
		//internalElements+=Type
		public Assignment getInternalElementsAssignment_4_0_1() { return cInternalElementsAssignment_4_0_1; }
		
		//Type
		public RuleCall getInternalElementsTypeParserRuleCall_4_0_1_0() { return cInternalElementsTypeParserRuleCall_4_0_1_0; }
		
		//'op' internalElements+=Operator
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//'op'
		public Keyword getOpKeyword_4_1_0() { return cOpKeyword_4_1_0; }
		
		//internalElements+=Operator
		public Assignment getInternalElementsAssignment_4_1_1() { return cInternalElementsAssignment_4_1_1; }
		
		//Operator
		public RuleCall getInternalElementsOperatorParserRuleCall_4_1_1_0() { return cInternalElementsOperatorParserRuleCall_4_1_1_0; }
		
		//'axm' internalElements+=Axiom
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//'axm'
		public Keyword getAxmKeyword_4_2_0() { return cAxmKeyword_4_2_0; }
		
		//internalElements+=Axiom
		public Assignment getInternalElementsAssignment_4_2_1() { return cInternalElementsAssignment_4_2_1; }
		
		//Axiom
		public RuleCall getInternalElementsAxiomParserRuleCall_4_2_1_0() { return cInternalElementsAxiomParserRuleCall_4_2_1_0; }
		
		//'thm' internalElements+=Theorem
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//'thm'
		public Keyword getThmKeyword_4_3_0() { return cThmKeyword_4_3_0; }
		
		//internalElements+=Theorem
		public Assignment getInternalElementsAssignment_4_3_1() { return cInternalElementsAssignment_4_3_1; }
		
		//Theorem
		public RuleCall getInternalElementsTheoremParserRuleCall_4_3_1_0() { return cInternalElementsTheoremParserRuleCall_4_3_1_0; }
		
		//'ruleblock' ruleBlocks+=RuleBlock
		public Group getGroup_4_4() { return cGroup_4_4; }
		
		//'ruleblock'
		public Keyword getRuleblockKeyword_4_4_0() { return cRuleblockKeyword_4_4_0; }
		
		//ruleBlocks+=RuleBlock
		public Assignment getRuleBlocksAssignment_4_4_1() { return cRuleBlocksAssignment_4_4_1; }
		
		//RuleBlock
		public RuleCall getRuleBlocksRuleBlockParserRuleCall_4_4_1_0() { return cRuleBlocksRuleBlockParserRuleCall_4_4_1_0; }
		
		//'end'
		public Keyword getEndKeyword_5() { return cEndKeyword_5; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Parameter");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Parameter:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Type");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cParametersAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cParametersParameterCrossReference_1_1_0 = (CrossReference)cParametersAssignment_1_1.eContents().get(0);
		private final RuleCall cParametersParameterIDTerminalRuleCall_1_1_0_1 = (RuleCall)cParametersParameterCrossReference_1_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConstructorsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConstructorsConstructorParserRuleCall_3_0 = (RuleCall)cConstructorsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVerticalLineKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cConstructorsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cConstructorsConstructorParserRuleCall_4_1_0 = (RuleCall)cConstructorsAssignment_4_1.eContents().get(0);
		
		//Type:
		//	name=ID ('(' parameters+=[Parameter]+ ')')?
		//	'=' constructors+=Constructor ('|' constructors+=Constructor)*;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ('(' parameters+=[Parameter]+ ')')? '=' constructors+=Constructor ('|' constructors+=Constructor)*
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//('(' parameters+=[Parameter]+ ')')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//parameters+=[Parameter]+
		public Assignment getParametersAssignment_1_1() { return cParametersAssignment_1_1; }
		
		//[Parameter]
		public CrossReference getParametersParameterCrossReference_1_1_0() { return cParametersParameterCrossReference_1_1_0; }
		
		//ID
		public RuleCall getParametersParameterIDTerminalRuleCall_1_1_0_1() { return cParametersParameterIDTerminalRuleCall_1_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//constructors+=Constructor
		public Assignment getConstructorsAssignment_3() { return cConstructorsAssignment_3; }
		
		//Constructor
		public RuleCall getConstructorsConstructorParserRuleCall_3_0() { return cConstructorsConstructorParserRuleCall_3_0; }
		
		//('|' constructors+=Constructor)*
		public Group getGroup_4() { return cGroup_4; }
		
		//'|'
		public Keyword getVerticalLineKeyword_4_0() { return cVerticalLineKeyword_4_0; }
		
		//constructors+=Constructor
		public Assignment getConstructorsAssignment_4_1() { return cConstructorsAssignment_4_1; }
		
		//Constructor
		public RuleCall getConstructorsConstructorParserRuleCall_4_1_0() { return cConstructorsConstructorParserRuleCall_4_1_0; }
	}
	public class ConstructorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Constructor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDestructorsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDestructorsDestructorParserRuleCall_1_1_0 = (RuleCall)cDestructorsAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cDestructorsAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cDestructorsDestructorParserRuleCall_1_2_1_0 = (RuleCall)cDestructorsAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//Constructor:
		//	name=ID ('(' destructors+=Destructor (',' destructors+=Destructor)* ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ('(' destructors+=Destructor (',' destructors+=Destructor)* ')')?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//('(' destructors+=Destructor (',' destructors+=Destructor)* ')')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//destructors+=Destructor
		public Assignment getDestructorsAssignment_1_1() { return cDestructorsAssignment_1_1; }
		
		//Destructor
		public RuleCall getDestructorsDestructorParserRuleCall_1_1_0() { return cDestructorsDestructorParserRuleCall_1_1_0; }
		
		//(',' destructors+=Destructor)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//','
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//destructors+=Destructor
		public Assignment getDestructorsAssignment_1_2_1() { return cDestructorsAssignment_1_2_1; }
		
		//Destructor
		public RuleCall getDestructorsDestructorParserRuleCall_1_2_1_0() { return cDestructorsDestructorParserRuleCall_1_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }
	}
	public class DestructorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Destructor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeSTRINGTerminalRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Destructor:
		//	name=ID ":" type=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ":" type=STRING
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//type=STRING
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//STRING
		public RuleCall getTypeSTRINGTerminalRuleCall_2_0() { return cTypeSTRINGTerminalRuleCall_2_0; }
	}
	public class OperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Operator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cArgumentsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cArgumentsArgumentParserRuleCall_1_1_0 = (RuleCall)cArgumentsAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cArgumentsAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cArgumentsArgumentParserRuleCall_1_2_1_0 = (RuleCall)cArgumentsAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cColonKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cTypeAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cTypeSTRINGTerminalRuleCall_2_0_1_0 = (RuleCall)cTypeAssignment_2_0_1.eContents().get(0);
		private final Assignment cNotationAssignment_2_1 = (Assignment)cUnorderedGroup_2.eContents().get(1);
		private final RuleCall cNotationNotationEnumRuleCall_2_1_0 = (RuleCall)cNotationAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cUnorderedGroup_2.eContents().get(2);
		private final Assignment cAssociativeAssignment_2_2_0 = (Assignment)cGroup_2_2.eContents().get(0);
		private final Keyword cAssociativeAssociativeKeyword_2_2_0_0 = (Keyword)cAssociativeAssignment_2_2_0.eContents().get(0);
		private final Assignment cCommutativeAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final Keyword cCommutativeCommutativeKeyword_2_2_1_0 = (Keyword)cCommutativeAssignment_2_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNumberSignKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPrecedentAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPrecedentINTTerminalRuleCall_3_1_0 = (RuleCall)cPrecedentAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cForKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cWdAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cWdSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cWdAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Alternatives cAlternatives_5_1 = (Alternatives)cGroup_5.eContents().get(1);
		private final Assignment cDefinitionAssignment_5_1_0 = (Assignment)cAlternatives_5_1.eContents().get(0);
		private final RuleCall cDefinitionSTRINGTerminalRuleCall_5_1_0_0 = (RuleCall)cDefinitionAssignment_5_1_0.eContents().get(0);
		private final Group cGroup_5_1_1 = (Group)cAlternatives_5_1.eContents().get(1);
		private final Keyword cCaseKeyword_5_1_1_0 = (Keyword)cGroup_5_1_1.eContents().get(0);
		private final Assignment cCaseAssignment_5_1_1_1 = (Assignment)cGroup_5_1_1.eContents().get(1);
		private final RuleCall cCaseIDTerminalRuleCall_5_1_1_1_0 = (RuleCall)cCaseAssignment_5_1_1_1.eContents().get(0);
		private final Assignment cCasesAssignment_5_1_1_2 = (Assignment)cGroup_5_1_1.eContents().get(2);
		private final RuleCall cCasesCaseParserRuleCall_5_1_1_2_0 = (RuleCall)cCasesAssignment_5_1_1_2.eContents().get(0);
		
		//Operator:
		//	name=ID ('(' arguments+=Argument (',' arguments+=Argument)* ')')? ((':' type=STRING)? & notation=Notation? &
		//	(associative?='associative' commutative?='commutative'?)?) ('#' precedent=INT)? ('for' wd=STRING)? ('='
		//	(definition=STRING
		//	|
		//	'case' case=ID cases+=Case+))?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ('(' arguments+=Argument (',' arguments+=Argument)* ')')? ((':' type=STRING)? & notation=Notation? &
		//(associative?='associative' commutative?='commutative'?)?) ('#' precedent=INT)? ('for' wd=STRING)? ('='
		//(definition=STRING | 'case' case=ID cases+=Case+))?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//('(' arguments+=Argument (',' arguments+=Argument)* ')')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//arguments+=Argument
		public Assignment getArgumentsAssignment_1_1() { return cArgumentsAssignment_1_1; }
		
		//Argument
		public RuleCall getArgumentsArgumentParserRuleCall_1_1_0() { return cArgumentsArgumentParserRuleCall_1_1_0; }
		
		//(',' arguments+=Argument)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//','
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//arguments+=Argument
		public Assignment getArgumentsAssignment_1_2_1() { return cArgumentsAssignment_1_2_1; }
		
		//Argument
		public RuleCall getArgumentsArgumentParserRuleCall_1_2_1_0() { return cArgumentsArgumentParserRuleCall_1_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }
		
		//(':' type=STRING)? & notation=Notation? & (associative?='associative' commutative?='commutative'?)?
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//(':' type=STRING)?
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//':'
		public Keyword getColonKeyword_2_0_0() { return cColonKeyword_2_0_0; }
		
		//type=STRING
		public Assignment getTypeAssignment_2_0_1() { return cTypeAssignment_2_0_1; }
		
		//STRING
		public RuleCall getTypeSTRINGTerminalRuleCall_2_0_1_0() { return cTypeSTRINGTerminalRuleCall_2_0_1_0; }
		
		//notation=Notation?
		public Assignment getNotationAssignment_2_1() { return cNotationAssignment_2_1; }
		
		//Notation
		public RuleCall getNotationNotationEnumRuleCall_2_1_0() { return cNotationNotationEnumRuleCall_2_1_0; }
		
		//(associative?='associative' commutative?='commutative'?)?
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//associative?='associative'
		public Assignment getAssociativeAssignment_2_2_0() { return cAssociativeAssignment_2_2_0; }
		
		//'associative'
		public Keyword getAssociativeAssociativeKeyword_2_2_0_0() { return cAssociativeAssociativeKeyword_2_2_0_0; }
		
		//commutative?='commutative'?
		public Assignment getCommutativeAssignment_2_2_1() { return cCommutativeAssignment_2_2_1; }
		
		//'commutative'
		public Keyword getCommutativeCommutativeKeyword_2_2_1_0() { return cCommutativeCommutativeKeyword_2_2_1_0; }
		
		//('#' precedent=INT)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'#'
		public Keyword getNumberSignKeyword_3_0() { return cNumberSignKeyword_3_0; }
		
		//precedent=INT
		public Assignment getPrecedentAssignment_3_1() { return cPrecedentAssignment_3_1; }
		
		//INT
		public RuleCall getPrecedentINTTerminalRuleCall_3_1_0() { return cPrecedentINTTerminalRuleCall_3_1_0; }
		
		//('for' wd=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'for'
		public Keyword getForKeyword_4_0() { return cForKeyword_4_0; }
		
		//wd=STRING
		public Assignment getWdAssignment_4_1() { return cWdAssignment_4_1; }
		
		//STRING
		public RuleCall getWdSTRINGTerminalRuleCall_4_1_0() { return cWdSTRINGTerminalRuleCall_4_1_0; }
		
		//('=' (definition=STRING | 'case' case=ID cases+=Case+))?
		public Group getGroup_5() { return cGroup_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_5_0() { return cEqualsSignKeyword_5_0; }
		
		//definition=STRING | 'case' case=ID cases+=Case+
		public Alternatives getAlternatives_5_1() { return cAlternatives_5_1; }
		
		//definition=STRING
		public Assignment getDefinitionAssignment_5_1_0() { return cDefinitionAssignment_5_1_0; }
		
		//STRING
		public RuleCall getDefinitionSTRINGTerminalRuleCall_5_1_0_0() { return cDefinitionSTRINGTerminalRuleCall_5_1_0_0; }
		
		//'case' case=ID cases+=Case+
		public Group getGroup_5_1_1() { return cGroup_5_1_1; }
		
		//'case'
		public Keyword getCaseKeyword_5_1_1_0() { return cCaseKeyword_5_1_1_0; }
		
		//case=ID
		public Assignment getCaseAssignment_5_1_1_1() { return cCaseAssignment_5_1_1_1; }
		
		//ID
		public RuleCall getCaseIDTerminalRuleCall_5_1_1_1_0() { return cCaseIDTerminalRuleCall_5_1_1_1_0; }
		
		//cases+=Case+
		public Assignment getCasesAssignment_5_1_1_2() { return cCasesAssignment_5_1_1_2; }
		
		//Case
		public RuleCall getCasesCaseParserRuleCall_5_1_1_2_0() { return cCasesCaseParserRuleCall_5_1_1_2_0; }
	}
	public class ArgumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Argument");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeSTRINGTerminalRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Argument:
		//	name=ID ":" type=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ":" type=STRING
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//type=STRING
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//STRING
		public RuleCall getTypeSTRINGTerminalRuleCall_2_0() { return cTypeSTRINGTerminalRuleCall_2_0; }
	}
	public class CaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Case");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPatternAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPatternSTRINGTerminalRuleCall_0_0 = (RuleCall)cPatternAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFormulaAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFormulaSTRINGTerminalRuleCall_2_0 = (RuleCall)cFormulaAssignment_2.eContents().get(0);
		
		//Case:
		//	pattern=STRING "=>" formula=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//pattern=STRING "=>" formula=STRING
		public Group getGroup() { return cGroup; }
		
		//pattern=STRING
		public Assignment getPatternAssignment_0() { return cPatternAssignment_0; }
		
		//STRING
		public RuleCall getPatternSTRINGTerminalRuleCall_0_0() { return cPatternSTRINGTerminalRuleCall_0_0; }
		
		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_1() { return cEqualsSignGreaterThanSignKeyword_1; }
		
		//formula=STRING
		public Assignment getFormulaAssignment_2() { return cFormulaAssignment_2; }
		
		//STRING
		public RuleCall getFormulaSTRINGTerminalRuleCall_2_0() { return cFormulaSTRINGTerminalRuleCall_2_0; }
	}
	public class AxiomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Axiom");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCommercialAtKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPredicateAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPredicateSTRINGTerminalRuleCall_3_0 = (RuleCall)cPredicateAssignment_3.eContents().get(0);
		
		//Axiom:
		//	'@' name=ID ':' predicate=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'@' name=ID ':' predicate=STRING
		public Group getGroup() { return cGroup; }
		
		//'@'
		public Keyword getCommercialAtKeyword_0() { return cCommercialAtKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//predicate=STRING
		public Assignment getPredicateAssignment_3() { return cPredicateAssignment_3; }
		
		//STRING
		public RuleCall getPredicateSTRINGTerminalRuleCall_3_0() { return cPredicateSTRINGTerminalRuleCall_3_0; }
	}
	public class TheoremElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Theorem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCommercialAtKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPredicateAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPredicateSTRINGTerminalRuleCall_3_0 = (RuleCall)cPredicateAssignment_3.eContents().get(0);
		
		//Theorem:
		//	'@' name=ID ':' predicate=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'@' name=ID ':' predicate=STRING
		public Group getGroup() { return cGroup; }
		
		//'@'
		public Keyword getCommercialAtKeyword_0() { return cCommercialAtKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//predicate=STRING
		public Assignment getPredicateAssignment_3() { return cPredicateAssignment_3; }
		
		//STRING
		public RuleCall getPredicateSTRINGTerminalRuleCall_3_0() { return cPredicateSTRINGTerminalRuleCall_3_0; }
	}
	public class RuleBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.RuleBlock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cVariablesKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cVariablesAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cVariablesVariableParserRuleCall_0_1_0 = (RuleCall)cVariablesAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cRuleKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cRulesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRulesRuleParserRuleCall_1_1_0 = (RuleCall)cRulesAssignment_1_1.eContents().get(0);
		
		//RuleBlock:
		//	('variables' variables+=Variable+)? ('rule' rules+=Rule)+;
		@Override public ParserRule getRule() { return rule; }
		
		//('variables' variables+=Variable+)? ('rule' rules+=Rule)+
		public Group getGroup() { return cGroup; }
		
		//('variables' variables+=Variable+)?
		public Group getGroup_0() { return cGroup_0; }
		
		//'variables'
		public Keyword getVariablesKeyword_0_0() { return cVariablesKeyword_0_0; }
		
		//variables+=Variable+
		public Assignment getVariablesAssignment_0_1() { return cVariablesAssignment_0_1; }
		
		//Variable
		public RuleCall getVariablesVariableParserRuleCall_0_1_0() { return cVariablesVariableParserRuleCall_0_1_0; }
		
		//('rule' rules+=Rule)+
		public Group getGroup_1() { return cGroup_1; }
		
		//'rule'
		public Keyword getRuleKeyword_1_0() { return cRuleKeyword_1_0; }
		
		//rules+=Rule
		public Assignment getRulesAssignment_1_1() { return cRulesAssignment_1_1; }
		
		//Rule
		public RuleCall getRulesRuleParserRuleCall_1_1_0() { return cRulesRuleParserRuleCall_1_1_0; }
	}
	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCommercialAtKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cRruleAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cRruleRewriteRuleParserRuleCall_3_0_0 = (RuleCall)cRruleAssignment_3_0.eContents().get(0);
		private final Assignment cIruleAssignment_3_1 = (Assignment)cAlternatives_3.eContents().get(1);
		private final RuleCall cIruleInferenceRuleParserRuleCall_3_1_0 = (RuleCall)cIruleAssignment_3_1.eContents().get(0);
		
		//Rule:
		//	'@' name=ID ':' (rrule=RewriteRule | irule=InferenceRule);
		@Override public ParserRule getRule() { return rule; }
		
		//'@' name=ID ':' (rrule=RewriteRule | irule=InferenceRule)
		public Group getGroup() { return cGroup; }
		
		//'@'
		public Keyword getCommercialAtKeyword_0() { return cCommercialAtKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//rrule=RewriteRule | irule=InferenceRule
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//rrule=RewriteRule
		public Assignment getRruleAssignment_3_0() { return cRruleAssignment_3_0; }
		
		//RewriteRule
		public RuleCall getRruleRewriteRuleParserRuleCall_3_0_0() { return cRruleRewriteRuleParserRuleCall_3_0_0; }
		
		//irule=InferenceRule
		public Assignment getIruleAssignment_3_1() { return cIruleAssignment_3_1; }
		
		//InferenceRule
		public RuleCall getIruleInferenceRuleParserRuleCall_3_1_0() { return cIruleInferenceRuleParserRuleCall_3_1_0; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeSTRINGTerminalRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Variable:
		//	name=ID ':' type=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ':' type=STRING
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//type=STRING
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//STRING
		public RuleCall getTypeSTRINGTerminalRuleCall_2_0() { return cTypeSTRINGTerminalRuleCall_2_0; }
	}
	public class RewriteRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.RewriteRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPatternAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPatternSTRINGTerminalRuleCall_0_0 = (RuleCall)cPatternAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Assignment cUruleAssignment_2_0 = (Assignment)cAlternatives_2.eContents().get(0);
		private final RuleCall cUruleUnconditionalRewriteParserRuleCall_2_0_0 = (RuleCall)cUruleAssignment_2_0.eContents().get(0);
		private final Assignment cCruleAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cCruleConditionalRewriteParserRuleCall_2_1_0 = (RuleCall)cCruleAssignment_2_1.eContents().get(0);
		
		//RewriteRule:
		//	pattern=STRING '==' (urule=UnconditionalRewrite | crule=ConditionalRewrite);
		@Override public ParserRule getRule() { return rule; }
		
		//pattern=STRING '==' (urule=UnconditionalRewrite | crule=ConditionalRewrite)
		public Group getGroup() { return cGroup; }
		
		//pattern=STRING
		public Assignment getPatternAssignment_0() { return cPatternAssignment_0; }
		
		//STRING
		public RuleCall getPatternSTRINGTerminalRuleCall_0_0() { return cPatternSTRINGTerminalRuleCall_0_0; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_1() { return cEqualsSignEqualsSignKeyword_1; }
		
		//urule=UnconditionalRewrite | crule=ConditionalRewrite
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//urule=UnconditionalRewrite
		public Assignment getUruleAssignment_2_0() { return cUruleAssignment_2_0; }
		
		//UnconditionalRewrite
		public RuleCall getUruleUnconditionalRewriteParserRuleCall_2_0_0() { return cUruleUnconditionalRewriteParserRuleCall_2_0_0; }
		
		//crule=ConditionalRewrite
		public Assignment getCruleAssignment_2_1() { return cCruleAssignment_2_1; }
		
		//ConditionalRewrite
		public RuleCall getCruleConditionalRewriteParserRuleCall_2_1_0() { return cCruleConditionalRewriteParserRuleCall_2_1_0; }
	}
	public class InferenceRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.InferenceRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cGivenAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cGivenGivenParserRuleCall_0_0 = (RuleCall)cGivenAssignment_0.eContents().get(0);
		private final Keyword cVerticalLineHyphenMinusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInferAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInferInferParserRuleCall_2_0 = (RuleCall)cInferAssignment_2.eContents().get(0);
		
		//InferenceRule:
		//	given+=Given* '|-' infer=Infer;
		@Override public ParserRule getRule() { return rule; }
		
		//given+=Given* '|-' infer=Infer
		public Group getGroup() { return cGroup; }
		
		//given+=Given*
		public Assignment getGivenAssignment_0() { return cGivenAssignment_0; }
		
		//Given
		public RuleCall getGivenGivenParserRuleCall_0_0() { return cGivenGivenParserRuleCall_0_0; }
		
		//'|-'
		public Keyword getVerticalLineHyphenMinusKeyword_1() { return cVerticalLineHyphenMinusKeyword_1; }
		
		//infer=Infer
		public Assignment getInferAssignment_2() { return cInferAssignment_2; }
		
		//Infer
		public RuleCall getInferInferParserRuleCall_2_0() { return cInferInferParserRuleCall_2_0; }
	}
	public class GivenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Given");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cExpressionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cExpressionSTRINGTerminalRuleCall_0_0 = (RuleCall)cExpressionAssignment_0.eContents().get(0);
		private final Assignment cRequiredAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cRequiredRequiredKeyword_1_0 = (Keyword)cRequiredAssignment_1.eContents().get(0);
		
		//Given:
		//	expression=STRING required?='required'?;
		@Override public ParserRule getRule() { return rule; }
		
		//expression=STRING required?='required'?
		public Group getGroup() { return cGroup; }
		
		//expression=STRING
		public Assignment getExpressionAssignment_0() { return cExpressionAssignment_0; }
		
		//STRING
		public RuleCall getExpressionSTRINGTerminalRuleCall_0_0() { return cExpressionSTRINGTerminalRuleCall_0_0; }
		
		//required?='required'?
		public Assignment getRequiredAssignment_1() { return cRequiredAssignment_1; }
		
		//'required'
		public Keyword getRequiredRequiredKeyword_1_0() { return cRequiredRequiredKeyword_1_0; }
	}
	public class InferElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Infer");
		private final Assignment cExpressionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cExpressionSTRINGTerminalRuleCall_0 = (RuleCall)cExpressionAssignment.eContents().get(0);
		
		//Infer:
		//	expression=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//expression=STRING
		public Assignment getExpressionAssignment() { return cExpressionAssignment; }
		
		//STRING
		public RuleCall getExpressionSTRINGTerminalRuleCall_0() { return cExpressionSTRINGTerminalRuleCall_0; }
	}
	public class UnconditionalRewriteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.UnconditionalRewrite");
		private final Assignment cRhsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cRhsSTRINGTerminalRuleCall_0 = (RuleCall)cRhsAssignment.eContents().get(0);
		
		//UnconditionalRewrite:
		//	rhs+=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//rhs+=STRING
		public Assignment getRhsAssignment() { return cRhsAssignment; }
		
		//STRING
		public RuleCall getRhsSTRINGTerminalRuleCall_0() { return cRhsSTRINGTerminalRuleCall_0; }
	}
	public class ConditionalRewriteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.ConditionalRewrite");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRewritesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cRewritesConditionalRewriteRuleParserRuleCall_0_0 = (RuleCall)cRewritesAssignment_0.eContents().get(0);
		private final Assignment cRewritesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRewritesConditionalRewriteRuleParserRuleCall_1_0 = (RuleCall)cRewritesAssignment_1.eContents().get(0);
		
		//ConditionalRewrite:
		//	rewrites+=ConditionalRewriteRule
		//	rewrites+=ConditionalRewriteRule*;
		@Override public ParserRule getRule() { return rule; }
		
		//rewrites+=ConditionalRewriteRule rewrites+=ConditionalRewriteRule*
		public Group getGroup() { return cGroup; }
		
		//rewrites+=ConditionalRewriteRule
		public Assignment getRewritesAssignment_0() { return cRewritesAssignment_0; }
		
		//ConditionalRewriteRule
		public RuleCall getRewritesConditionalRewriteRuleParserRuleCall_0_0() { return cRewritesConditionalRewriteRuleParserRuleCall_0_0; }
		
		//rewrites+=ConditionalRewriteRule*
		public Assignment getRewritesAssignment_1() { return cRewritesAssignment_1; }
		
		//ConditionalRewriteRule
		public RuleCall getRewritesConditionalRewriteRuleParserRuleCall_1_0() { return cRewritesConditionalRewriteRuleParserRuleCall_1_0; }
	}
	public class ConditionalRewriteRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.ConditionalRewriteRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLhsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLhsSTRINGTerminalRuleCall_0_0 = (RuleCall)cLhsAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRhsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRhsSTRINGTerminalRuleCall_2_0 = (RuleCall)cRhsAssignment_2.eContents().get(0);
		
		//ConditionalRewriteRule:
		//	lhs=STRING '=>' rhs=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//lhs=STRING '=>' rhs=STRING
		public Group getGroup() { return cGroup; }
		
		//lhs=STRING
		public Assignment getLhsAssignment_0() { return cLhsAssignment_0; }
		
		//STRING
		public RuleCall getLhsSTRINGTerminalRuleCall_0_0() { return cLhsSTRINGTerminalRuleCall_0_0; }
		
		//'=>'
		public Keyword getEqualsSignGreaterThanSignKeyword_1() { return cEqualsSignGreaterThanSignKeyword_1; }
		
		//rhs=STRING
		public Assignment getRhsAssignment_2() { return cRhsAssignment_2; }
		
		//STRING
		public RuleCall getRhsSTRINGTerminalRuleCall_2_0() { return cRhsSTRINGTerminalRuleCall_2_0; }
	}
	
	public class NotationElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ac.soton.xtheory.Theory.Notation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPREFIXEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPREFIXPrefixKeyword_0_0 = (Keyword)cPREFIXEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cINFIXEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cINFIXInfixKeyword_1_0 = (Keyword)cINFIXEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPOSTFIXEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPOSTFIXPostfixKeyword_2_0 = (Keyword)cPOSTFIXEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Notation:
		//	PREFIX='prefix' | INFIX='infix' | POSTFIX='postfix';
		public EnumRule getRule() { return rule; }
		
		//PREFIX='prefix' | INFIX='infix' | POSTFIX='postfix'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PREFIX='prefix'
		public EnumLiteralDeclaration getPREFIXEnumLiteralDeclaration_0() { return cPREFIXEnumLiteralDeclaration_0; }
		
		//'prefix'
		public Keyword getPREFIXPrefixKeyword_0_0() { return cPREFIXPrefixKeyword_0_0; }
		
		//INFIX='infix'
		public EnumLiteralDeclaration getINFIXEnumLiteralDeclaration_1() { return cINFIXEnumLiteralDeclaration_1; }
		
		//'infix'
		public Keyword getINFIXInfixKeyword_1_0() { return cINFIXInfixKeyword_1_0; }
		
		//POSTFIX='postfix'
		public EnumLiteralDeclaration getPOSTFIXEnumLiteralDeclaration_2() { return cPOSTFIXEnumLiteralDeclaration_2; }
		
		//'postfix'
		public Keyword getPOSTFIXPostfixKeyword_2_0() { return cPOSTFIXPostfixKeyword_2_0; }
	}
	
	private final TheoryElements pTheory;
	private final ParameterElements pParameter;
	private final TypeElements pType;
	private final ConstructorElements pConstructor;
	private final DestructorElements pDestructor;
	private final OperatorElements pOperator;
	private final ArgumentElements pArgument;
	private final NotationElements eNotation;
	private final CaseElements pCase;
	private final AxiomElements pAxiom;
	private final TheoremElements pTheorem;
	private final RuleBlockElements pRuleBlock;
	private final RuleElements pRule;
	private final VariableElements pVariable;
	private final RewriteRuleElements pRewriteRule;
	private final InferenceRuleElements pInferenceRule;
	private final GivenElements pGiven;
	private final InferElements pInfer;
	private final UnconditionalRewriteElements pUnconditionalRewrite;
	private final ConditionalRewriteElements pConditionalRewrite;
	private final ConditionalRewriteRuleElements pConditionalRewriteRule;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TheoryGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTheory = new TheoryElements();
		this.pParameter = new ParameterElements();
		this.pType = new TypeElements();
		this.pConstructor = new ConstructorElements();
		this.pDestructor = new DestructorElements();
		this.pOperator = new OperatorElements();
		this.pArgument = new ArgumentElements();
		this.eNotation = new NotationElements();
		this.pCase = new CaseElements();
		this.pAxiom = new AxiomElements();
		this.pTheorem = new TheoremElements();
		this.pRuleBlock = new RuleBlockElements();
		this.pRule = new RuleElements();
		this.pVariable = new VariableElements();
		this.pRewriteRule = new RewriteRuleElements();
		this.pInferenceRule = new InferenceRuleElements();
		this.pGiven = new GivenElements();
		this.pInfer = new InferElements();
		this.pUnconditionalRewrite = new UnconditionalRewriteElements();
		this.pConditionalRewrite = new ConditionalRewriteElements();
		this.pConditionalRewriteRule = new ConditionalRewriteRuleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ac.soton.xtheory.Theory".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////import "platform:/ressource/ac.soton.eventb.emf.core.theoryextension/model/eventbcoretheoryextension.ecore"
	//Theory:
	//	'theory' name=ID ('(' parameters+=Parameter+ ')')? ('import' imports+=ID imports+=ID*)? ('type' internalElements+=Type
	//	| 'op' internalElements+=Operator | 'axm' internalElements+=Axiom | 'thm' internalElements+=Theorem | 'ruleblock'
	//	ruleBlocks+=RuleBlock)*
	//	'end';
	public TheoryElements getTheoryAccess() {
		return pTheory;
	}
	
	public ParserRule getTheoryRule() {
		return getTheoryAccess().getRule();
	}
	
	//Parameter:
	//	name=ID;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//Type:
	//	name=ID ('(' parameters+=[Parameter]+ ')')?
	//	'=' constructors+=Constructor ('|' constructors+=Constructor)*;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Constructor:
	//	name=ID ('(' destructors+=Destructor (',' destructors+=Destructor)* ')')?;
	public ConstructorElements getConstructorAccess() {
		return pConstructor;
	}
	
	public ParserRule getConstructorRule() {
		return getConstructorAccess().getRule();
	}
	
	//Destructor:
	//	name=ID ":" type=STRING;
	public DestructorElements getDestructorAccess() {
		return pDestructor;
	}
	
	public ParserRule getDestructorRule() {
		return getDestructorAccess().getRule();
	}
	
	//Operator:
	//	name=ID ('(' arguments+=Argument (',' arguments+=Argument)* ')')? ((':' type=STRING)? & notation=Notation? &
	//	(associative?='associative' commutative?='commutative'?)?) ('#' precedent=INT)? ('for' wd=STRING)? ('='
	//	(definition=STRING
	//	|
	//	'case' case=ID cases+=Case+))?;
	public OperatorElements getOperatorAccess() {
		return pOperator;
	}
	
	public ParserRule getOperatorRule() {
		return getOperatorAccess().getRule();
	}
	
	//Argument:
	//	name=ID ":" type=STRING;
	public ArgumentElements getArgumentAccess() {
		return pArgument;
	}
	
	public ParserRule getArgumentRule() {
		return getArgumentAccess().getRule();
	}
	
	//enum Notation:
	//	PREFIX='prefix' | INFIX='infix' | POSTFIX='postfix';
	public NotationElements getNotationAccess() {
		return eNotation;
	}
	
	public EnumRule getNotationRule() {
		return getNotationAccess().getRule();
	}
	
	//Case:
	//	pattern=STRING "=>" formula=STRING;
	public CaseElements getCaseAccess() {
		return pCase;
	}
	
	public ParserRule getCaseRule() {
		return getCaseAccess().getRule();
	}
	
	//Axiom:
	//	'@' name=ID ':' predicate=STRING;
	public AxiomElements getAxiomAccess() {
		return pAxiom;
	}
	
	public ParserRule getAxiomRule() {
		return getAxiomAccess().getRule();
	}
	
	//Theorem:
	//	'@' name=ID ':' predicate=STRING;
	public TheoremElements getTheoremAccess() {
		return pTheorem;
	}
	
	public ParserRule getTheoremRule() {
		return getTheoremAccess().getRule();
	}
	
	//RuleBlock:
	//	('variables' variables+=Variable+)? ('rule' rules+=Rule)+;
	public RuleBlockElements getRuleBlockAccess() {
		return pRuleBlock;
	}
	
	public ParserRule getRuleBlockRule() {
		return getRuleBlockAccess().getRule();
	}
	
	//Rule:
	//	'@' name=ID ':' (rrule=RewriteRule | irule=InferenceRule);
	public RuleElements getRuleAccess() {
		return pRule;
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}
	
	//Variable:
	//	name=ID ':' type=STRING;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//RewriteRule:
	//	pattern=STRING '==' (urule=UnconditionalRewrite | crule=ConditionalRewrite);
	public RewriteRuleElements getRewriteRuleAccess() {
		return pRewriteRule;
	}
	
	public ParserRule getRewriteRuleRule() {
		return getRewriteRuleAccess().getRule();
	}
	
	//InferenceRule:
	//	given+=Given* '|-' infer=Infer;
	public InferenceRuleElements getInferenceRuleAccess() {
		return pInferenceRule;
	}
	
	public ParserRule getInferenceRuleRule() {
		return getInferenceRuleAccess().getRule();
	}
	
	//Given:
	//	expression=STRING required?='required'?;
	public GivenElements getGivenAccess() {
		return pGiven;
	}
	
	public ParserRule getGivenRule() {
		return getGivenAccess().getRule();
	}
	
	//Infer:
	//	expression=STRING;
	public InferElements getInferAccess() {
		return pInfer;
	}
	
	public ParserRule getInferRule() {
		return getInferAccess().getRule();
	}
	
	//UnconditionalRewrite:
	//	rhs+=STRING;
	public UnconditionalRewriteElements getUnconditionalRewriteAccess() {
		return pUnconditionalRewrite;
	}
	
	public ParserRule getUnconditionalRewriteRule() {
		return getUnconditionalRewriteAccess().getRule();
	}
	
	//ConditionalRewrite:
	//	rewrites+=ConditionalRewriteRule
	//	rewrites+=ConditionalRewriteRule*;
	public ConditionalRewriteElements getConditionalRewriteAccess() {
		return pConditionalRewrite;
	}
	
	public ParserRule getConditionalRewriteRule() {
		return getConditionalRewriteAccess().getRule();
	}
	
	//ConditionalRewriteRule:
	//	lhs=STRING '=>' rhs=STRING;
	public ConditionalRewriteRuleElements getConditionalRewriteRuleAccess() {
		return pConditionalRewriteRule;
	}
	
	public ParserRule getConditionalRewriteRuleRule() {
		return getConditionalRewriteRuleAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
